version: '3.8'

services:
  ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./app:/app
      - ./data:/data
    restart: unless-stopped